<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>1.0.0.0</Version>
    <Author>yjohnson-dev</Author>
    <Name>Blackout</Name>
    <Punchline>Turns the screen black while you're away.</Punchline>
    <Description>Fades the screen to black when the game is in the background or when you are away from the keyboard. This should help prevent OLED burn-in on TVs and monitors, or to remove in-game distractions when working on something else.</Description>
    <Tags>oled;burn-in;afk;utility</Tags>
    <RepoUrl>https://github.com/yjohnson-dev/xiv-blackout</RepoUrl>

    <!-- The build runs in a Linux container. This value permits the net10.0-windows target. -->
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
</Project>
